#!/bin/sh

OPTS=`getopt -o o: --long output: \
     -n $0 -- "$@"`

eval set -- "$OPTS"

OUTPUT=skr.oot

while true ; do
	case "$1" in
        -o|--output) OUTPUT=$2 ; shift 2 ;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
	esac
done

THIS="`realpath \"$0\"`"
LOCATION="`dirname \"$THIS\"`"            # relative
LOCATION="`( cd \"$LOCATION\" && pwd )`"  # absolutized and normalized
if [ -z "$LOCATION" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1  # fail
fi

LOGFILE=`pwd`/$OUTPUT
echo "+ scrutinizing: '$@'"
echo "+ log at: $LOGFILE"
export LD_PRELOAD=libdl.so:$LOCATION/libskroot.so:$LD_PRELOAD
export SKROOT_FILE=$LOGFILE

$@